### ISSUE TITLE
Property use_odometry==false can lead to crashes

### ISSUE THREAD

**Issue by pierrewillenbrockdfki** [dfki-ric/orogen-slam3d#2]
When the property `use_odometry` is set to false there are a few opportunities to access the `mOdometry` object even though it is `nullptr`. Two can be reached by "normal" means, while one can only be reached through the `transformer_callback`:

1) Do a normal Start with `use_odometry=true`
2) Do Stop+Cleanup; set `use_odometry=false`
3) Do Configure+Start
4) The transformer_callback will still be called because it has been registered in the Configure while `use_odometry==true`

Here is a version that avoids the accesses through `mOdometry`. One may want to also protect the access inside `transformer_callback`. I am not sure if the mathematical results are correct.

https://github.com/pierrewillenbrockdfki/ric-orogen-slam3d/tree/workarounds-for-use_odometry-false

**Comment by pierrewillenbrockdfki** [comment]
@skasperski

**Comment by skasperski** [comment]
Please test if https://github.com/dfki-ric/orogen-slam3d/tree/devel fixes this issue for you.

**Comment by pierrewillenbrockdfki** [comment]
> Please test if https://github.com/dfki-ric/orogen-slam3d/tree/devel fixes this issue for you.

That seems to work fine.
